### ISSUE TITLE
How to make DIV2K_train_LR_bicubic images ?

### ISSUE THREAD

**Issue by BaeSukkyoung** [sanghyun-son/EDSR-PyTorch#317]
I want to train the EDSR with my own imageset.

Then, how can I make LR_bicubic images ?

Is there any code or it should be going by myself ?

**Comment by ulfailliyina** [comment]
try the code https://github.com/RakeshRaj97/downsampling-images-x2-super-resolution

**Comment by 1632325673** [comment]
hello，i also train the EDSR with my own imageset,but I have encountered this problem, have you encountered it
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument
[1600/16000]    [L1: 17.1081]   6.4+47.0s
[3200/16000]    [L1: 11.4710]   6.6+7.4s
[4800/16000]    [L1: 9.1921]    7.5+9.3s
[6400/16000]    [L1: 7.8708]    6.4+6.4s
[8000/16000]    [L1: 7.0100]    8.1+9.7s
[9600/16000]    [L1: 6.4434]    7.3+7.8s
[11200/16000]   [L1: 6.0191]    8.5+12.8s
[12800/16000]   [L1: 5.6959]    9.4+14.7s
[14400/16000]   [L1: 5.4452]    7.3+10.3s
[16000/16000]   [L1: 5.2218]    7.2+9.8s

Evaluation:
0it [00:00, ?it/s]
[div2k x2]      PSNR: nan (Best: nan @epoch 1)
Forward: 2.87s

Saving...
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 28, in main
    t.test()
  File "/data2/qinfl/EDSR/src/trainer.py", line 123, in test
    self.ckp.save(self, epoch, is_best=(best[1][0, 0] + 1 == epoch))
  File "/data2/qinfl/EDSR/src/utility.py", line 97, in save
    self.plot_psnr(epoch)
  File "/data2/qinfl/EDSR/src/utility.py", line 124, in plot_psnr
    label='Scale {}'.format(scale)
  File "/data2/qinfl/YES/envs/EDSR1/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2842, in plot
    **({"data": data} if data is not None else {}), **kwargs)
  File "/data2/qinfl/YES/envs/EDSR1/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 1743, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/data2/qinfl/YES/envs/EDSR1/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 273, in __call__
    yield from self._plot_args(this, kwargs)
  File "/data2/qinfl/YES/envs/EDSR1/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 399, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (0,) and (1,)
